### ISSUE TITLE
Check connection state

### ISSUE THREAD

**Issue by a-i-ks** [baselsw/BPLib#1]
Hey Basel,
many thanks for this library. How does your software connection check work? 
What is connected to your pin 7?
I’m trying to realize a Bluetooth Presence Detection. I want to trigger events when a smartphone automatically connects to the BlueSMiRF HID. Using the HID profile was the only possibility to enable the automatically connection of a iPhone. Now I just need to check if a device is connected to the module. Maybe you know a way to realize this with my Arduino UNO? Many thanks in advance for your help.
Regards André

**Comment by baselsw** [comment]
Hey,

Pin 7 is connected to the "Connect LED indicator" directly to the module.. I don't know if the "CONNECT LED" is broken out on the BlueSMiRF module.. But if there is a "CONNECT LED" on-board, then you could probably solder a wire from the led to for example, pin 7.

//Basel
